paths:
  /api/roles/post:
    post:
      tags:
        - Roles
      summary: 'Add new role'
      description: Add new role in database.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/role'
      responses:
        '200':
          description: New role add.
        '422':
          description: This role is already registered.