paths:
  /api/roles/{id}:
    get:
      tags:
        - Get role by id
      summary: 'Get role by id'
      description: Get role by id from database.
      parameters:
        - name: id
          in: path
          description: ID of the role to retrieve.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Get role by id from database.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/role'
        '422':
          description: Could not fetch role by id.
