// Teacher register data body model

const teacher = {
  name: "Jose",
  lastName: "Perez",
  phone: "34243423",
  dni: "342324324",
  birthDate: "05/08/1999",
  address: "Calle falsa 123",
  roleId: 1,
};

// Classes register to teacher

const clase = {
  className: "Matemáticas",
  commissions: [
    //? Autogenerated commissions with coupon limit?
    {
      id: 1,
      commissionNumber: 23213,
    },
    {
      id: 2,
      commissionNumber: 23214,
    },
    {
      id: 3,
      commissionNumber: 23215,
    },
    {
      id: 4,
      commissionNumber: 23216,
    },
  ],
};

// Student register data body model

const student = {
  name: "Carlos",
  lastName: "Perez",
  phone: "34243323",
  dni: "342324465",
  birthDate: "05/08/1995",
  address: "Calle falsa 123",
  roleId: 2,
  careerId: 1,
};
//* Auto insert student in availability commissions from classes
